#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path

import yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def normalize_zone(host_pattern: str) -> str:
    host = host_pattern.strip().lower()
    if host == "*":
        return "."
    if host.startswith("*."):
        return host[2:]
    return host


def load_zones(policy_path: Path) -> list[str]:
    raw = yaml.safe_load(policy_path.read_text(encoding="utf-8"))
    if raw is None:
        return []
    if not isinstance(raw, dict):
        raise ValueError("allow-list.yaml must contain a mapping at top level")

    zones = {normalize_zone(str(host)) for host in raw.keys()}
    zones.discard("")
    if "." in zones:
        return ["."]
    return sorted(zones)


def render_corefile(zones: list[str]) -> str:
    lines: list[str] = [
        "# Auto-generated by infra/coredns/generate-corefile.py",
        "# Source: infra/mitmproxy/allow-list.yaml",
        "",
    ]

    if not zones:
        lines.extend(
            [
                ".:5353 {",
                "    bufsize 512",
                "    template ANY ANY {",
                "        rcode REFUSED",
                "    }",
                "    log",
                "    errors",
                "    cache 60",
                "}",
                "",
            ]
        )
        return "\n".join(lines)

    if "." in zones:
        lines.extend(
            [
                ".:5353 {",
                "    bufsize 512",
                "    forward . 127.0.0.11:53",
                "    log",
                "    errors",
                "    cache 60",
                "}",
                "",
            ]
        )
        return "\n".join(lines)

    lines.extend(
        [
            ".:5353 {",
            "    bufsize 512",
            "    template ANY ANY {",
            "        rcode REFUSED",
            "    }",
            "    log",
            "    errors",
            "    cache 60",
            "}",
            "",
        ]
    )

    for zone in zones:
        lines.extend(
            [
                f"{zone}:5353 {{",
                "    bufsize 512",
                "    forward . 127.0.0.11:53",
                "    log",
                "    errors",
                "    cache 60",
                "}",
                "",
            ]
        )

    return "\n".join(lines)


def main() -> None:
    args = parse_args()
    zones = load_zones(args.input)
    corefile = render_corefile(zones)
    args.output.write_text(corefile, encoding="utf-8")


if __name__ == "__main__":
    main()
